/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#8f003f",
        "surface-tint": "#902fb4",
        "secondary": "#b90c55",
        "surface-container-high": "#f6e1ff",
        "primary": "#700095",
        "inverse-on-surface": "#fbecff",
        "secondary-fixed-dim": "#ffb1c2",
        "error-container": "#ffdad6",
        "secondary-container": "#fe4d86",
        "surface-dim": "#ead1f8",
        "surface-bright": "#fff7fd",
        "on-secondary-fixed": "#3f0018",
        "on-primary-fixed-variant": "#75079a",
        "surface-container": "#f9e8ff",
        "outline-variant": "#d2c1d3",
        "surface-variant": "#f2daff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#f9d8ff",
        "on-error": "#ffffff",
        "tertiary-container": "#5e576a",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#590025",
        "on-primary-fixed": "#320046",
        "on-tertiary-container": "#d8cee4",
        "primary-container": "#8b2ab0",
        "surface": "#fff7fd",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#edb1ff",
        "background": "#fff7fd",
        "on-background": "#251431",
        "surface-container-low": "#fcefff",
        "on-tertiary-fixed-variant": "#4a4456",
        "tertiary": "#464052",
        "error": "#ba1a1a",
        "on-surface": "#251431",
        "on-primary-container": "#f2c1ff",
        "inverse-surface": "#3b2947",
        "on-tertiary": "#ffffff",
        "outline": "#817382",
        "surface-container-highest": "#f2daff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1e1929",
        "on-surface-variant": "#4f4351",
        "tertiary-fixed-dim": "#cdc2d9",
        "inverse-primary": "#edb1ff",
        "secondary-fixed": "#ffd9df",
        "tertiary-fixed": "#e9def5"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "container-max": "1280px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "headline-lg": ["Playfair Display"],
        "headline-xl": ["Playfair Display"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Playfair Display"]
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["60px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "300" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "700" }]
      }
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}